In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('nasa.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
Nasa=pd.read_csv("C:/Users/sanka/OneDrive/Desktop/dataset/nasa.csv",squeeze=True)

In [5]:
Nasa.isnull().sum()

Neo Reference ID                0
Name                            0
Absolute Magnitude              0
Est Dia in KM(min)              0
Est Dia in KM(max)              0
Est Dia in M(min)               0
Est Dia in M(max)               0
Est Dia in Miles(min)           0
Est Dia in Miles(max)           0
Est Dia in Feet(min)            0
Est Dia in Feet(max)            0
Close Approach Date             0
Epoch Date Close Approach       0
Relative Velocity km per sec    0
Relative Velocity km per hr     0
Miles per hour                  0
Miss Dist.(Astronomical)        0
Miss Dist.(lunar)               0
Miss Dist.(kilometers)          0
Miss Dist.(miles)               0
Orbiting Body                   0
Orbit ID                        0
Orbit Determination Date        0
Orbit Uncertainity              0
Minimum Orbit Intersection      0
Jupiter Tisserand Invariant     0
Epoch Osculation                0
Eccentricity                    0
Semi Major Axis                 0
Inclination   

In [6]:
Nasa.drop("Name",axis=1,inplace=True)
Nasa.drop("Equinox",axis=1,inplace=True)
Nasa.drop("Neo Reference ID",axis=1,inplace=True)
Nasa.drop("Est Dia in M(max)",axis=1,inplace=True)
Nasa.drop("Est Dia in M(min)",axis=1,inplace=True)
Nasa.drop("Est Dia in KM(min)",axis=1,inplace=True)
Nasa.drop("Est Dia in KM(max)",axis=1,inplace=True)
Nasa.drop("Miss Dist.(miles)",axis=1,inplace=True)
Nasa.drop("Miss Dist.(kilometers)",axis=1,inplace=True)
Nasa.drop("Miss Dist.(Astronomical)",axis=1,inplace=True)
Nasa.drop("Relative Velocity km per hr",axis=1,inplace=True)
Nasa.drop("Close Approach Date",axis=1,inplace=True)
Nasa.drop("Epoch Date Close Approach",axis=1,inplace=True)
Nasa.drop("Orbit ID",axis=1,inplace=True)
Nasa.drop("Orbit Determination Date",axis=1,inplace=True)
Nasa.drop("Orbiting Body",axis=1,inplace=True)

In [7]:
Nasa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4687 entries, 0 to 4686
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Absolute Magnitude            4687 non-null   float64
 1   Est Dia in Miles(min)         4687 non-null   float64
 2   Est Dia in Miles(max)         4687 non-null   float64
 3   Est Dia in Feet(min)          4687 non-null   float64
 4   Est Dia in Feet(max)          4687 non-null   float64
 5   Relative Velocity km per sec  4687 non-null   float64
 6   Miles per hour                4687 non-null   float64
 7   Miss Dist.(lunar)             4687 non-null   float64
 8   Orbit Uncertainity            4687 non-null   int64  
 9   Minimum Orbit Intersection    4687 non-null   float64
 10  Jupiter Tisserand Invariant   4687 non-null   float64
 11  Epoch Osculation              4687 non-null   float64
 12  Eccentricity                  4687 non-null   float64
 13  Sem

In [8]:
Nasa.head()

Absolute Magnitude  Est Dia in Miles(min)  Est Dia in Miles(max)  \
0                21.6               0.079051               0.176763   
1                21.3               0.090762               0.202951   
2                20.3               0.143849               0.321655   
3                27.4               0.005469               0.012229   
4                21.6               0.079051               0.176763   

   Est Dia in Feet(min)  Est Dia in Feet(max)  Relative Velocity km per sec  \
0            417.388066            933.308089                      6.115834   
1            479.225620           1071.581063                     18.113985   
2            759.521423           1698.341531                      7.590711   
3             28.876199             64.569144                     11.173874   
4            417.388066            933.308089                      9.840831   

   Miles per hour  Miss Dist.(lunar)  Orbit Uncertainity  \
0    13680.509944         163.178711                   5   
1    40519.173105         148.992630                   3   
2    16979.661798          19.821890                   0   
3    24994.839864         110.990387                   6   
4    22012.954985         158.646713                   1   

   Minimum Orbit Intersection  ...  Inclination  Asc Node Longitude  \
0                    0.025282  ...     6.025981          314.373913   
1                    0.186935  ...    28.412996          136.717242   
2                    0.043058  ...     4.237961          259.475979   
3                    0.005512  ...     7.905894           57.173266   
4                    0.034798  ...    16.793382           84.629307   

   Orbital Period  Perihelion Distance  Perihelion Arg  Aphelion Dist  \
0      609.599786             0.808259       57.257470       2.005764   
1      425.869294             0.718200      313.091975       1.497352   
2      643.580228             0.950791      248.415038       1.966857   
3      514.082140             0.983902       18.707701       1.527904   
4      495.597821             0.967687      158.263596       1.483543   

   Perihelion Time  Mean Anomaly  Mean Motion  Hazardous  
0     2.458162e+06    264.837533     0.590551       True  
1     2.457795e+06    173.741112     0.845330      False  
2     2.458120e+06    292.893654     0.559371       True  
3     2.457902e+06     68.741007     0.700277      False  
4     2.457814e+06    135.142133     0.726395       True  

[5 rows x 24 columns]

In [18]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()
X= encoder.fit_transform(X)
print(X)

[[2835. 2835.  104. ... 2664. 1632.    0.]
 [3007. 3007.   92. ... 1758. 2559.    0.]
 [ 599.  599.   75. ... 2934. 1520.    0.]
 ...
 [3470. 3470.  128. ... 2047. 1380.    0.]
 [3471. 3471.  107. ... 2048. 1460.    0.]
 [3623. 3623.   55. ... 1868. 1484.    0.]]


In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[1 0 1 ... 0 0 0]


In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [21]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
X_train = mms.fit_transform(X_train)
X_test = mms.transform(X_test)
print(X_test)

[[0.74993227 0.74993227 0.79477612 ... 0.06962883 0.20845758 0.        ]
 [0.10864264 0.10864264 0.25       ... 0.30533731 0.35483871 0.        ]
 [0.46654023 0.46654023 0.53358209 ... 0.66458954 0.97370561 0.        ]
 ...
 [0.89975616 0.89975616 0.82089552 ... 0.29124898 0.63404717 0.        ]
 [0.25358981 0.25358981 0.71268657 ... 0.70035221 0.78286799 0.        ]
 [0.8233541  0.8233541  0.28731343 ... 0.06366838 0.99620493 0.        ]]


In [22]:
from catboost import CatBoostClassifier
classifier=CatBoostClassifier(iterations=80,  learning_rate=0.07,  loss_function='MultiClass',  thread_count=6,
                         random_seed=47,)
classifier.fit(X_train, y_train,eval_set=(X_test, y_test),plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.6317456	test: 0.6329571	best: 0.6329571 (0)	total: 159ms	remaining: 12.6s
1:	learn: 0.5767519	test: 0.5783330	best: 0.5783330 (1)	total: 170ms	remaining: 6.61s
2:	learn: 0.5285701	test: 0.5307455	best: 0.5307455 (2)	total: 180ms	remaining: 4.62s
3:	learn: 0.4841860	test: 0.4869675	best: 0.4869675 (3)	total: 190ms	remaining: 3.61s
4:	learn: 0.4447834	test: 0.4481974	best: 0.4481974 (4)	total: 200ms	remaining: 3s
5:	learn: 0.4093422	test: 0.4128414	best: 0.4128414 (5)	total: 210ms	remaining: 2.59s
6:	learn: 0.3787584	test: 0.3824751	best: 0.3824751 (6)	total: 220ms	remaining: 2.29s
7:	learn: 0.3502532	test: 0.3538765	best: 0.3538765 (7)	total: 229ms	remaining: 2.06s
8:	learn: 0.3250966	test: 0.3287133	best: 0.3287133 (8)	total: 239ms	remaining: 1.88s
9:	learn: 0.3015628	test: 0.3055927	best: 0.3055927 (9)	total: 248ms	remaining: 1.74s
10:	learn: 0.2796174	test: 0.2841143	best: 0.2841143 (10)	total: 258ms	remaining: 1.62s
11:	learn: 0.2599306	test: 0.2646279	best: 0.2646279 (1

In [29]:
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
print('Precision: %.3f' % precision_score(y_test, y_pred))
print('Recall: %.3f' % recall_score(y_test, y_pred))

Precision: 0.993
Recall: 0.966


In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[792   1]
 [  5 140]]


0.9936034115138592

In [31]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

0:	learn: 0.6309449	total: 9.97ms	remaining: 787ms
1:	learn: 0.5760799	total: 19ms	remaining: 740ms
2:	learn: 0.5283256	total: 27.5ms	remaining: 707ms
3:	learn: 0.4840138	total: 35.9ms	remaining: 683ms
4:	learn: 0.4450340	total: 44.3ms	remaining: 664ms
5:	learn: 0.4095780	total: 53ms	remaining: 653ms
6:	learn: 0.3792616	total: 61.7ms	remaining: 643ms
7:	learn: 0.3504082	total: 70.2ms	remaining: 632ms
8:	learn: 0.3249973	total: 78.9ms	remaining: 622ms
9:	learn: 0.3014768	total: 87.6ms	remaining: 613ms
10:	learn: 0.2796238	total: 96ms	remaining: 602ms
11:	learn: 0.2601571	total: 105ms	remaining: 594ms
12:	learn: 0.2425846	total: 114ms	remaining: 586ms
13:	learn: 0.2263008	total: 123ms	remaining: 579ms
14:	learn: 0.2106651	total: 132ms	remaining: 573ms
15:	learn: 0.1966278	total: 143ms	remaining: 571ms
16:	learn: 0.1835361	total: 152ms	remaining: 564ms
17:	learn: 0.1716050	total: 161ms	remaining: 556ms
18:	learn: 0.1606975	total: 171ms	remaining: 549ms
19:	learn: 0.1509247	total: 180ms	re