In [68]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [97]:
Nasa=pd.read_csv("C:/Users/sanka/OneDrive/Desktop/dataset/NASABALANCED.csv",squeeze=True)

In [98]:
Nasa.isnull().sum()

Neo Reference ID                0
Name                            0
Absolute Magnitude              0
Est Dia in KM(min)              0
Est Dia in KM(max)              0
Est Dia in M(min)               0
Est Dia in M(max)               0
Est Dia in Miles(min)           0
Est Dia in Miles(max)           0
Est Dia in Feet(min)            0
Est Dia in Feet(max)            0
Close Approach Date             0
Epoch Date Close Approach       0
Relative Velocity km per sec    0
Relative Velocity km per hr     0
Miles per hour                  0
Miss Dist.(Astronomical)        0
Miss Dist.(lunar)               0
Miss Dist.(kilometers)          0
Miss Dist.(miles)               0
Orbiting Body                   0
Orbit ID                        0
Orbit Determination Date        0
Orbit Uncertainity              0
Minimum Orbit Intersection      0
Jupiter Tisserand Invariant     0
Epoch Osculation                0
Eccentricity                    0
Semi Major Axis                 0
Inclination   

In [99]:
Nasa.drop("Name",axis=1,inplace=True)
Nasa.drop("Equinox",axis=1,inplace=True)
Nasa.drop("Neo Reference ID",axis=1,inplace=True)
Nasa.drop("Est Dia in M(max)",axis=1,inplace=True)
Nasa.drop("Est Dia in M(min)",axis=1,inplace=True)
Nasa.drop("Est Dia in KM(min)",axis=1,inplace=True)
Nasa.drop("Est Dia in KM(max)",axis=1,inplace=True)
Nasa.drop("Miss Dist.(miles)",axis=1,inplace=True)
Nasa.drop("Miss Dist.(kilometers)",axis=1,inplace=True)
Nasa.drop("Miss Dist.(Astronomical)",axis=1,inplace=True)
Nasa.drop("Relative Velocity km per hr",axis=1,inplace=True)
Nasa.drop("Close Approach Date",axis=1,inplace=True)
Nasa.drop("Epoch Date Close Approach",axis=1,inplace=True)
Nasa.drop("Orbit ID",axis=1,inplace=True)
Nasa.drop("Orbit Determination Date",axis=1,inplace=True)
Nasa.drop("Orbiting Body",axis=1,inplace=True)


In [100]:
Nasa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1511 entries, 0 to 1510
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Absolute Magnitude            1511 non-null   float64
 1   Est Dia in Miles(min)         1511 non-null   float64
 2   Est Dia in Miles(max)         1511 non-null   float64
 3   Est Dia in Feet(min)          1511 non-null   float64
 4   Est Dia in Feet(max)          1511 non-null   float64
 5   Relative Velocity km per sec  1511 non-null   float64
 6   Miles per hour                1511 non-null   float64
 7   Miss Dist.(lunar)             1511 non-null   float64
 8   Orbit Uncertainity            1511 non-null   int64  
 9   Minimum Orbit Intersection    1511 non-null   float64
 10  Jupiter Tisserand Invariant   1511 non-null   float64
 11  Epoch Osculation              1511 non-null   float64
 12  Eccentricity                  1511 non-null   float64
 13  Sem

In [101]:
Nasa.head()

Absolute Magnitude  Est Dia in Miles(min)  Est Dia in Miles(max)  \
0                28.5               0.003295               0.007369   
1                26.5               0.008278               0.018509   
2                24.7               0.018963               0.042402   
3                21.7               0.075493               0.168807   
4                23.1               0.039619               0.088591   

   Est Dia in Feet(min)  Est Dia in Feet(max)  Relative Velocity km per sec  \
0             17.399631             38.906757                      6.772390   
1             43.705896             97.729354                      7.433746   
2            100.124423            223.885017                      6.746674   
3            398.602509            891.302306                      1.795434   
4            209.189570            467.762099                     15.411512   

   Miles per hour  Miss Dist.(lunar)  Orbit Uncertainity  \
0     15149.16012         176.399017                   6   
1     16628.54607           5.517520                   7   
2     15091.63516          14.281188                   7   
3      4016.20520         121.280136                   3   
4     34474.01069          21.352867                   8   

   Minimum Orbit Intersection  ...  Inclination  Asc Node Longitude  \
0                    0.001675  ...    10.422884          345.832505   
1                    0.011573  ...     3.265515          127.016744   
2                    0.013692  ...     3.896475          145.187114   
3                    0.276284  ...     3.475969          160.374083   
4                    0.017829  ...     4.777926          292.426436   

   Orbital Period  Perihelion Distance  Perihelion Arg  Aphelion Dist  \
0      560.610573             0.834201      245.899764       1.826964   
1      432.237174             0.849893       87.095637       1.387690   
2      480.007801             0.915154      296.608808       1.484396   
3      839.455582             1.264681      354.824496       2.218394   
4      911.643064             0.789359      280.097596       2.890639   

   Perihelion Time  Mean Anomaly  Mean Motion  Hazardous  
0      2457918.727     52.511196     0.642157      False  
1      2458052.927    316.334925     0.832876      False  
2      2458089.761    293.055008     0.749988      False  
3      2458402.546    187.582988     0.428849      False  
4      2456747.069    336.871599     0.394891      False  

[5 rows x 24 columns]

In [102]:
Nasa.to_csv('nasadropbalanced.csv')

In [108]:
dataset = pd.read_csv('nasadropbalanced.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [199]:
df=pd.read_csv("nasadropbalanced.csv",squeeze=True)

df.head()

Unnamed: 0  Absolute Magnitude  Est Dia in Miles(min)  \
0           0                28.5               0.003295   
1           1                26.5               0.008278   
2           2                24.7               0.018963   
3           3                21.7               0.075493   
4           4                23.1               0.039619   

   Est Dia in Miles(max)  Est Dia in Feet(min)  Est Dia in Feet(max)  \
0               0.007369             17.399631             38.906757   
1               0.018509             43.705896             97.729354   
2               0.042402            100.124423            223.885017   
3               0.168807            398.602509            891.302306   
4               0.088591            209.189570            467.762099   

   Relative Velocity km per sec  Miles per hour  Miss Dist.(lunar)  \
0                      6.772390     15149.16012         176.399017   
1                      7.433746     16628.54607           5.517520   
2                      6.746674     15091.63516          14.281188   
3                      1.795434      4016.20520         121.280136   
4                     15.411512     34474.01069          21.352867   

   Orbit Uncertainity  ...  Inclination  Asc Node Longitude  Orbital Period  \
0                   6  ...    10.422884          345.832505      560.610573   
1                   7  ...     3.265515          127.016744      432.237174   
2                   7  ...     3.896475          145.187114      480.007801   
3                   3  ...     3.475969          160.374083      839.455582   
4                   8  ...     4.777926          292.426436      911.643064   

   Perihelion Distance  Perihelion Arg  Aphelion Dist  Perihelion Time  \
0             0.834201      245.899764       1.826964      2457918.727   
1             0.849893       87.095637       1.387690      2458052.927   
2             0.915154      296.608808       1.484396      2458089.761   
3             1.264681      354.824496       2.218394      2458402.546   
4             0.789359      280.097596       2.890639      2456747.069   

   Mean Anomaly  Mean Motion  Hazardous  
0     52.511196     0.642157      False  
1    316.334925     0.832876      False  
2    293.055008     0.749988      False  
3    187.582988     0.428849      False  
4    336.871599     0.394891      False  

[5 rows x 25 columns]

In [206]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)


In [222]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [223]:
print(y_test)

[0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 0 1 1 0 1 1 0 0 0 0 1 0 0
 0 1 1 0 0 1 0 0 0 1 0 0 1 1 1 0 0 0 0 1 1 0 1 1 1 1 1 0 1 0 0 1 1 0 0 0 0
 1 0 0 0 1 0 0 0 0 0 1 1 0 1 0 1 0 1 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 0 1 1
 0 0 1 1 0 0 1 0 0 0 1 0 0 0 1 1 1 0 0 1 1 1 0 1 0 1 1 1 1 0 1 1 0 1 1 0 1
 1 1 1 0 0 1 1 1 0 1 0 0 0 0 1 1 1 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 0 0 1 0 0
 0 0 1 1 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 1 1 1 1 0
 0 1 0 0 1 1 1 1 0 1 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 1 0 0 0 1 0 0 0 1 0 1 0
 0 1 0 0 1 0 1 0 1 1 1 1 0 1 0 0 0 0 1 0 1 1 0 1 1 0 1 0 1 1 1 0 1 1 1 1 1
 1 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 0 1 0 0 1 0 1
 1 1 0 1 1 0 1 0 0 1 1 1 0 0 1 1 0 1 0 1 0 0 1 1 0 1 1 1 0 1 1 1 0 0 1 1 0
 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 1 1 0 1 1 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 1 0
 1 1 1 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 0 0 1 1 0 1 0 1 1 0 1 0 0 1 1 1 1 0 1
 1 1 1 1 0 0 0 0 0 1]


In [224]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
X_train = mms.fit_transform(X_train)
X_test = mms.transform(X_test)
print(X_test)

[[0.53703704 0.01763171 0.01763171 ... 0.92121303 0.70945257 0.3624716 ]
 [0.62345679 0.00897965 0.00897965 ... 0.88009298 0.174493   0.11777177]
 [0.41975309 0.04310095 0.04310095 ... 0.88229766 0.44739671 0.45617877]
 ...
 [0.56790123 0.01388695 0.01388695 ... 0.76965409 0.11298538 0.28230979]
 [0.27160494 0.1313258  0.1313258  ... 0.90568079 0.96794259 0.4285744 ]
 [0.41358025 0.04515937 0.04515937 ... 0.90665312 0.95980865 0.32409024]]


In [234]:
from catboost import CatBoostClassifier
classifier=CatBoostClassifier(iterations=80,  learning_rate=0.07,  loss_function='MultiClass',  thread_count=6,
                         random_seed=47,)
classifier.fit(X_train, y_train,eval_set=(X_test, y_test),plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.6366190	test: 0.6373914	best: 0.6373914 (0)	total: 9.07ms	remaining: 716ms
1:	learn: 0.5884028	test: 0.5888976	best: 0.5888976 (1)	total: 14.8ms	remaining: 577ms
2:	learn: 0.5427162	test: 0.5436771	best: 0.5436771 (2)	total: 24ms	remaining: 616ms
3:	learn: 0.5005644	test: 0.5020050	best: 0.5020050 (3)	total: 30.8ms	remaining: 585ms
4:	learn: 0.4650156	test: 0.4674535	best: 0.4674535 (4)	total: 41ms	remaining: 614ms
5:	learn: 0.4318726	test: 0.4344781	best: 0.4344781 (5)	total: 47.6ms	remaining: 587ms
6:	learn: 0.4020674	test: 0.4048404	best: 0.4048404 (6)	total: 55.8ms	remaining: 581ms
7:	learn: 0.3721217	test: 0.3749382	best: 0.3749382 (7)	total: 60.3ms	remaining: 542ms
8:	learn: 0.3464785	test: 0.3497636	best: 0.3497636 (8)	total: 66.5ms	remaining: 525ms
9:	learn: 0.3240793	test: 0.3278082	best: 0.3278082 (9)	total: 71.4ms	remaining: 500ms
10:	learn: 0.3035253	test: 0.3078609	best: 0.3078609 (10)	total: 76.2ms	remaining: 478ms
11:	learn: 0.2836014	test: 0.2884172	best: 0.

In [235]:
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
print('Precision: %.3f' % precision_score(y_test, y_pred))
print('Recall: %.3f' % recall_score(y_test, y_pred))

Precision: 0.987
Recall: 0.987


In [236]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[230   1]
 [  2 221]]


0.9933920704845814

In [237]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

0:	learn: 0.6364176	total: 7.29ms	remaining: 576ms
1:	learn: 0.5889601	total: 12.7ms	remaining: 495ms
2:	learn: 0.5430103	total: 19.1ms	remaining: 491ms
3:	learn: 0.5006660	total: 24.4ms	remaining: 464ms
4:	learn: 0.4635207	total: 29.6ms	remaining: 444ms
5:	learn: 0.4306943	total: 34.1ms	remaining: 421ms
6:	learn: 0.4013321	total: 39.1ms	remaining: 408ms
7:	learn: 0.3715952	total: 43.8ms	remaining: 394ms
8:	learn: 0.3459869	total: 49.2ms	remaining: 388ms
9:	learn: 0.3265340	total: 54.5ms	remaining: 382ms
10:	learn: 0.3057548	total: 59.8ms	remaining: 375ms
11:	learn: 0.2860399	total: 65.1ms	remaining: 369ms
12:	learn: 0.2673492	total: 70.3ms	remaining: 362ms
13:	learn: 0.2502883	total: 75.6ms	remaining: 357ms
14:	learn: 0.2363194	total: 81.5ms	remaining: 353ms
15:	learn: 0.2239111	total: 87.2ms	remaining: 349ms
16:	learn: 0.2103589	total: 92.9ms	remaining: 344ms
17:	learn: 0.1982244	total: 98.7ms	remaining: 340ms
18:	learn: 0.1873214	total: 105ms	remaining: 336ms
19:	learn: 0.1764673	to